name: Build

on: [push]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      run: sudo apt-get install gcc-arm-none-eabi -y
    - name: Build sbtools
      run: |
        sudo apt-get install libcrypto++6 libcrypto++-dev libusb-1.0-0-dev -y
        cd tools/sbtools
        make
        cd ../..
    - name: Cmake configure
      run: cmake .
    - name : Cmake build
      run: cmake --build .
    - name: Upload OSLoader.sb
      uses: actions/upload-artifact@v2.2.2
      with:
        name: OSLoader.sb
        path: ./OSLoader/OSLoader.sb
    - name: Upload ExistOS.sys
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ExistOS.sys
        path: ./System/ExistOS.sys
    - name: Get Time
      id: get_time
      run: echo ::set-output name=TIME::$(date +%Y%m%d-%H%M%S)
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag:  ${{ steps.get_version.outputs.VERSION }}-${{ steps.get_time.outputs.TIME }}
        title: Automatically build file.
        prerelease: false
        files: |
          ./System/ExistOS.sys
          ./OSLoader/OSLoader.sb
