name: CMake

on: [push]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: arm-none-eabi-gcc
      run: sudo apt-get install gcc-arm-none-eabi -y
    - name: Build sbtools
      run: |
        sudo apt-get install libcrypto++6 libcrypto++-dev libusb-1.0-0-dev -y
        cd tools/sbtools
        make
        cd ../..
    - name: Cmake configure
      run: cmake .
    - name : Cmake build
      run: cmake --build .
    - name: Upload OSLoader.sb
      uses: actions/upload-artifact@v2.2.2
      with:
        name: OSLoader.sb
        path: ./OSLoader/OSLoader.sb
    - name: Upload ExistOS.sys
      uses: actions/upload-artifact@v2.2.2
      with:
        name: ExistOS.sys
        path: ./System/ExistOS.sys
